services:
  # Backend API Service
  - type: web
    name: steganography-api
    runtime: docker
    rootDir: backend
    envVars:
      - key: AWS_ACCESS_KEY_ID
        sync: false  # Set this manually in Render dashboard
      - key: AWS_SECRET_ACCESS_KEY
        sync: false  # Set this manually in Render dashboard
      - key: AWS_S3_BUCKET_NAME
        value: steganography001
      - key: AWS_S3_REGION
        value: us-east-1
    healthCheckPath: /docs
    
  # Frontend Web Application
  - type: web
    name: steganography-frontend
    runtime: docker
    rootDir: frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://steganography-api.onrender.com
